export {useDepartments} from './useDepartments.ts'
export {useCourses} from './useCourses.ts'
export {useRequest} from './useRequest.ts'
export {useWallet} from './useWallet.ts'
export {useModal} from './useModal.ts'
